### ISSUE TITLE
use vim-plug install，get error “invalid reference: master ”

### ISSUE THREAD

**Issue by NerDante** [glepnir/zephyr-nvim#3]
1. Add this plug to vim-plug list like this:
```shell
 Plug 'glepnir/zephyr-nvim' 
```
2 .  excute  PlugInstall in normal mode, I get a error:
>- Finishing ... Done!                                                               
> x zephyr-nvim:                                                                    
>  fatal: invalid reference: master

**Comment by glepnir** [comment]
github use `main` branch now. not master branch.

**Comment by TalAmuyal** [comment]
It could be solved by reinstalling the plugin.
I've done it thus:
1. Comment out the `Plug 'glepnir/zephyr-nvim'` line (and save)
2. Reopen Neovim
3. Run `:PlugClean`
4. Uncomment
5. Reopen Neovim
6. Run `:PlugInstall`

**Comment by blentz100** [comment]
I was getting this error message with 3 plugins and couldn't figure the solution. I understand that github is no longer using master as the default branch, but that didn't help me figure out how to clear the errors.

I tried the steps above from @TalAmuyal multiple times and still no luck.

Then I thought, maybe my installation of vim-plug itself was out of date. 

That led me to the installation page for vim-plug: https://github.com/junegunn/vim-plug

And there I noticed there were different installation instructions for vim and neovim. When I originally started using vim-plug it was with vim. I've since migrated to neovim. I did some checking and noticed my installation for vim-plug was in the spot that vim looks for it: 

`~/.vim/autoload/plug.vim`

I then went ahead and followed the installation instructions for neovim, and vim-plug was installed at:

`"${XDG_DATA_HOME:-$HOME/.local/share}"`

I retried the 6 steps above, it still didn't fix the issue but it looked like I was now using a slightly different version of vim-plug. It seemed to run faster and had a slightly different interface. My guess was it was now pointing to the vim-plug I just installed for neovim.

Then I deleted the vim-plug installed originally for vim at `~/.vim/autoload/plug.vim`

Doing that finally cleared the error. 

Hope this is helpful for anyone else that might be experiencing this issue.

**Comment by huyz** [comment]
@blentz100 Thanks for the tip. TL;DR: deleting `~/.vim/autoload/plug.vim` might fix your problem if you have switched from vim to neovim recently.

**Comment by freddyrangel** [comment]
> I was getting this error message with 3 plugins and couldn't figure the solution. I understand that github is no longer using master as the default branch, but that didn't help me figure out how to clear the errors.
> 
> I tried the steps above from @TalAmuyal multiple times and still no luck.
> 
> Then I thought, maybe my installation of vim-plug itself was out of date.
> 
> That led me to the installation page for vim-plug: https://github.com/junegunn/vim-plug
> 
> And there I noticed there were different installation instructions for vim and neovim. When I originally started using vim-plug it was with vim. I've since migrated to neovim. I did some checking and noticed my installation for vim-plug was in the spot that vim looks for it:
> 
> `~/.vim/autoload/plug.vim`
> 
> I then went ahead and followed the installation instructions for neovim, and vim-plug was installed at:
> 
> `"${XDG_DATA_HOME:-$HOME/.local/share}"`
> 
> I retried the 6 steps above, it still didn't fix the issue but it looked like I was now using a slightly different version of vim-plug. It seemed to run faster and had a slightly different interface. My guess was it was now pointing to the vim-plug I just installed for neovim.
> 
> Then I deleted the vim-plug installed originally for vim at `~/.vim/autoload/plug.vim`
> 
> Doing that finally cleared the error.
> 
> Hope this is helpful for anyone else that might be experiencing this issue.

I found out that I'm using an old version of vim-plug. Running `:PlugUpgrade` to update vim-plug, restarting vim, and then runnng `:PlugUpdate` to update all the plugins fixed the issue
